# Site settings
title: Carmichael Futsal
description: Our mission is to provide a fun, safe, and affordable soccer game for the community that facilitates skilled soccer play.
url: http://carmichaelfutsal.com

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
