# Site settings
title: Carmichael Futsal
description: test
url: http://carmichaelfutsal.com

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
